codecov:
  require_ci_to_pass: true

coverage:
  range: "70..100"
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: false
    patch:
      default:
        target: auto
        threshold: 0%
        informational: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - examples/**
  - "mocks/**"
  - "**/*_mock.go"
  - "**/mocks/**"
