on:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22.x, 1.23.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run go fmt
        if: runner.os != 'Windows'
        run: make fmt

      - name: Run golangci-lint
        if: runner.os != 'Windows'
        uses: golangci/golangci-lint-action@v6

      - name: Run go test
        run: make test

      - name: Upload coverage to Codecov
        if: runner.os != 'Windows'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
